### PR TITLE
cleanup logging

### PR DESCRIPTION
**Pull request by NicBOMB**
This branch unifies the various methods for logging into a single import from the common Utils.
This branch also moves the message helper from CilentDataHolderVR to the client utils.
Duplicate checkGLerror functions were unified in the VRPassHelper.
Some `org.vivecraft.common.utils.Utils.logger.` can be shortened to just `Utils.` when the client Utils for math functions are removed.

### CODE REVIEW

**Comment by ferriarnus** [comment]
2 Classes named utils isn't really good imo. I need to look at why it's even needed for the logger to be split, but in case we need common and client classes, we should call them `CommonUtil` and `ClientUtil` or something.

**Comment by fayer3** [comment]
the common.utils.Utils class is from me

**Comment by ferriarnus** [comment]
Doesn't really matter where it came from, but if we are using both in the same file, imports get messy. We might need a split because of access to the `Minecraft` instance, but then we need to change the names so it's more clear which is safe to call.

**Comment by fayer3** [comment]
closing as all system outs were changed to loggers with #284

**Pull request closed without merging**
