### PR TITLE
Setup Github actions

### PR DESCRIPTION
**Pull request by whywhywhyw**
Title says it all.
The Actions script can be copied to any branch and it will just work.

### CODE REVIEW

**Comment by ghost** [comment]
looks good, but the file size is unusually small... Have you tested the actual artifacts?

**Comment by whywhywhyw** [comment]
It may not be copying the assets.

**Comment by whywhywhyw** [comment]
Just modified it to upload the logs.

**Comment by whywhywhyw** [comment]
[4_Build with Gradle.txt](https://github.com/ferriarnus/VivecraftMod/files/10125823/4_Build.with.Gradle.txt)

**Comment by whywhywhyw** [comment]
I do not know what to do with the logs.

**Comment by ghost** [comment]
i can see lots of mod-related errors for some reason

**Comment by ghost** [comment]
@whywhywhyw huh... it seems like all that was output was a one-line manifest file

**Comment by whywhywhyw** [comment]
It may have something to do with the fact I am trying to build the Multiloader branch.

**Comment by ghost** [comment]
don't think so, try stealing the FabricMC build script, and see if that works

**Comment by whywhywhyw** [comment]
Not sure if it will work since this mod use achitectury

**Comment by ghost** [comment]
i also don't have any experience with the architectury api, you might be able to copy from another repo though

**Comment by ghost** [comment]
after looking into it, it seems like the jar is created, but then it errors out when trying to grab all the libraries, and crashes. When told to upload artifacts, it puts up the incomplete jars.

**Comment by whywhywhyw** [comment]
I probably need to write it to manually pull the libraries.

**Comment by whywhywhyw** [comment]
Or it may be the fact that I need to make it setup apache maven.

**Comment by ghost** [comment]
you also have access to a full command-line in actions (literally a full vm), with linux (don't know what actions has for windows) you could `apt-get install [java]` or `wget [lib]` and run it that way

**Pull request closed without merging**
