### PR TITLE
Added Traditional Chinese (zh_tw.json)

### PR DESCRIPTION
**Pull request by dirtTW**
Added Traditional Chinese localization

### CODE REVIEW

**Comment by fayer3** [comment]
hm, thanks, but could you do that here?
https://www.transifex.com/techjar/vivecraft/
we use that site for translation stuff

**Comment by fayer3** [comment]
also the zh_tw lang code is for Traditional Chinese for Taiwan.
not clear if that was intended or not

**Comment by fayer3** [comment]
if you have any questions you can join the main Vivecraft discord, and ask in the #translation-station channel https://discord.gg/eCZvCVe

**Comment by dirtTW** [comment]
> hm, thanks, but could you do that here? https://www.transifex.com/techjar/vivecraft/ we use that site for translation stuff

yeah sure

**Comment by fayer3** [comment]
if oyu don't get accepted soon, ping techjar in the mentioned discord

**Pull request closed without merging**
