### PR TITLE
add Parchment mappings

### PR DESCRIPTION
**Pull request by NicBOMB**
I've been using them on recommendation from @fayer3 a few months ago and can confirm they have been very helpful.

### CODE REVIEW

**Comment by ferriarnus** [comment]
Oh we didn't have parchement set up? Yeah it's good to add it.

**Comment by fayer3** [comment]
if we add Parchment we should also go through, and change all arguments to the parchment names, imo

**Comment by ferriarnus** [comment]
If we have some mojang names like p_037392, then yeah it would be worth to update those. Changing "color" to "pColor" is not worth it imo. That also doesn't *need* to be part of this PR, but it could be nice to do it here.

**Comment by NicBOMB** [comment]
> if we add Parchment we should also go through, and change all arguments to the parchment names, imo

> If we have some mojang names like p_037392, then yeah it would be worth to update those. Changing "color" to "pColor" is not worth it imo. That also doesn't _need_ to be part of this PR, but it could be nice to do it here.

I was going to make those changes in the add parchment mappings commit, but decided against it. Adding it to the build and using it should be separate commits. I can add another commit applying Parchment names to this PR.

**Pull request closed without merging**
