### PR TITLE
Detect garbage collector and warn if not ZGC on a capable system

### PR DESCRIPTION
**Pull request by Techjar**
~~This is a draft because we still need to create the guide and put the proper link in the code.~~

https://github.com/Vivecraft/VivecraftMod/wiki/Memory-and-GC-Setup

### CODE REVIEW

**Comment by fayer3** [comment]
could you fix the lang conflict and run the code formatter? I noticed your PRs don't use it.

**Comment by Techjar** [comment]
I don't know how to run the formatter.

**Comment by Techjar** [comment]
You mean Code > Reformat Code/File in Idea? I clicked that and it didn't really change anything. Added braces around an if statement, that's about it.

**Comment by fayer3** [comment]
yeah that's it, mostly the missing brackets, also do an `optimize imports` if possible, to not leave unused ones behind.
can do it on the whole java packet with those settings (righ click > reformat code. in the project view)
grafik

**Comment by fayer3** [comment]
yeah just the imports that are in the wrong order now

**Pull request merged**
